				<footer class="footer text-right">
					<span class="pull-left"><strong><?= SITE_NAME ?></strong> <small>v21.11.0 <small>beta</small></small></span>
					© <?= date('Y') ?> <?= SITE_NAME ?>
				</footer>
			</div>
		</div>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/jquery/jquery.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/bootstrap/js/popper.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/js/jquery.slimscroll.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/js/waves.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/js/sidebarmenu.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/moment/min/moment.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/js/custom.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/sparkline/jquery.sparkline.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/blockUI/jquery.blockUI.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/sweetalert/sweetalert.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/typeahead.js-master/dist/typeahead.bundle.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/js/mask.init.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/datatables/jquery.dataTables.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/datatables/dataTables.buttons.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/datatables/jszip.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/datatables/buttons.html5.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/session-timeout/jquery.sessionTimeout.min.js"></script>
		<script type="text/javascript" src="<?=URL_ROOT?>/assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
		<script type="text/javascript" src="<?= URL_ROOT ?>/assets/plugins/dropify/dist/js/dropify.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/toast/toastr.min.js"></script>

		<script>
			$(function(){

			});
		</script>
	</body>
</html>