<?php
if(array_search('/usuarios', array_column($_SESSION['permisos'], 'url')) !== false) header('Location: '.URL_ROOT.'/usuarios');
/* if(array_search('/tiendita', array_column($_SESSION['permisos'], 'url')) !== false) header('Location: '.URL_ROOT.'/tiendita');
if(array_search('/comunidades', array_column($_SESSION['permisos'], 'url')) !== false) header('Location: '.URL_ROOT.'/comunidades');
if(array_search('/produccion', array_column($_SESSION['permisos'], 'url')) !== false) header('Location: '.URL_ROOT.'/produccion'); */
?>