<?php require_once './core/defines.php'; ?>
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="icon" type="image/png" sizes="16x16" href="<?=URL_ROOT?>/assets/images/favicon_w.png">
		<title><?= SITE_NAME ?></title>
		<link href="<?=URL_ROOT?>/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="<?=URL_ROOT?>/assets/css/style.css" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="<?=URL_ROOT?>/assets/plugins/sweetalert/sweetalert.css" />
		<link href="<?=URL_ROOT?>/assets/css/colors/blue.css" id="theme" rel="stylesheet">
		<style>
			.footer { left: 0; background-color: transparent; }
		</style>
	</head>
	<body style="background: linear-gradient(180deg,#de1be3 0,#0574f0); color: #212529;">
		<div class="preloader">
			<svg class="circular" viewBox="25 25 50 50">
				<circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
		</div>
		<section id="wrapper" class="p-t-30 p-b-30">
			<!-- <div class="row"> -->
				<div class="col-sm-6 offset-sm-3 text-center">
					<div class="card card-default">
						<div class="card-body">
							<div class="text-center">
								<img src="<?=URL_ROOT?>/assets/images/wef-banner.jpg" class="img img-responsive" id="logo">
								<hr>
							</div>

							<div id="frm-registro">
								<p><strong>Women Economic Forum</strong> será el 21 y 22 de marzo en <strong>Camino Real Polanco</strong>, <a href="https://goo.gl/maps/7jg8pXqKuS99kquG9" target="_blank" rel="noopener noreferrer">Calz. Gral. Mariano Escobedo 700, Anzures, Miguel Hidalgo, 11590 Ciudad de México, CDMX</a></p> 
								<p>La cita es a las 8:45 am ambos días. Puedes consultar la agenda completa en <a href="https://wefiberoamerica.com/women-economic-forum/agenda/" target="_blank" rel="noopener noreferrer">este link</a>.</p>
								<p>A continuación, deberás completar el formulario. <br><small>* - Esto significa que es obligatorio.</small></p>
								<div class="form col-sm-6 offset-sm-3">
									<div class="form-group">
										<label for="reg-nombre" class="form-label">Nombre *</label>
  										<input type="text" class="form-control" id="reg-nombre" placeholder="Nombre (s)">
									</div>
									<div class="form-group">
										<label for="reg-paterno" class="form-label">Primer Apellido *</label>
  										<input type="text" class="form-control" id="reg-paterno" placeholder="Apellido Paterno">
									</div>
									<div class="form-group">
										<label for="reg-materno" class="form-label">Segundo Apellido *</label>
  										<input type="text" class="form-control" id="reg-materno" placeholder="Apellido materno">
									</div>
									<div class="form-group">
										<label for="reg-empresa" class="form-label">Empresa *</label>
										  <input type="text" class="form-control" id="reg-empresa" placeholder="Nombre de la Empresa">
									</div>
									<div class="form-group">
										<label for="reg-cargo" class="form-label">Puesto *</label>
										  <input type="text" class="form-control" id="reg-cargo" placeholder="Puesto">
									</div>
									<div class="form-group">
										<label for="reg-email" class="form-label">Email *</label>
  										<input type="email" class="form-control" id="reg-email" placeholder="Correo electrónico">
									</div>
									<div class="form-group">
										<label for="reg-telefono" class="form-label">Teléfono *</label>
										  <input type="tel" class="form-control" id="reg-telefono" placeholder="Teléfono">
									</div>
									<div class="form-group hide">
										<label for="reg-tipo" class="form-label">Voy como *</label>
										<select id="reg-tipo" class="form-control">
											<option value="">Selecciona</option>
											<option value="Speaker" <?= $tipo=='speaker'?'selected':'' ?>>Speaker</option>
											<option value="Patrocinador" <?= $tipo=='patrocinador'?'selected':'' ?>>Patrocinador</option>
											<option value="Invitado" <?= $tipo=='invitado'?'selected':'' ?>>Invitado</option>
											<option value="Prensa" <?= $tipo=='prensa'?'selected':'' ?>>Prensa</option>
											<option value="Staff" <?= $tipo=='staff'?'selected':'' ?>>Staff</option>
										</select>
									</div>
									<div class="form-group invitado  <?= $tipo!='invitado'?'hide':'' ?>">
										<label for="reg-invitado" class="form-label">Empresa que lo invitó *</label>
										  <input type="text" class="form-control" id="reg-invitado" placeholder="Empresa que lo invitó">
									</div>
									<div class="form-group">
										<label for="reg-asiste" class="form-label">Asisteré el día *</label>
										<select id="reg-asiste" class="form-control">
											<option value="">Selecciona</option>
											<option value="21 y 22">21 y 22 de Marzo</option>
											<option value="21">21 de Marzo</option>
											<option value="22">22 de Marzo</option>
										</select>
									</div>
									<button class="btn btn-info btn-lg text-uppercase waves-effect waves-light" id="btnRegistro" type="button">Continuar</button>
								</div>
							</div>

							<div id="frm-res" style="display: none;">
								<div id="message-success" role="alert" class="hide">
									<h4 class="alert-heading">¡Listo! Has quedado confirmado al evento <strong>Women Economic Forum</strong></h4>
									<p>Este es tu código el cual deberás presentar el día del evento. </p>
									<p class="display-5"></p>
									<img id="imgQR" src="" alt="qr" class="img-responsive img-thumbnail" style="max-width: 300px;">
									<br><br>
									<h5 class="alert-heading"><strong>Te invitamos a que descargues este PDF. El cual contiene tu acceso para el evento.</strong></h5>
									<button type="button" class="btn btn-sm waves-effect waves-light" style="border: 2px solid #1e3365" id="btnDescargar"><span class="fa fa-qrcode"></span> Descargar PDF</button>
									<br><br>
									<p>
										Te esperamos el día <span class="dias"></span> de marzo <br> 
										Camino Real Polanco <br>
										Calz. Gral. Mariano Escobedo 700, Anzures, Miguel Hidalgo, 11590 Ciudad de México, CDMX, México.
									</p>
									<p>
										Consulta la <a href="https://wefiberoamerica.com/women-economic-forum/agenda/" target="_blank" rel="noopener noreferrer">Agenda del Evento</a>.
									</p>
								</div>
							</div>

							<br>
							<hr class="m-t-30 m-b-30">
							Si necesitas asistencia, puedes escribir <br> a: <a href="mailto:brenda.santamaria@wefiberoamerica.com">brenda.santamaria@wefiberoamerica.com</a> o <a href="mailto:jorge@wefiberoamerica.com">jorge@wefiberoamerica.com</a> 
							<br><br>
							<small>Aviso de privacidad <br> <a href="https://tecnoregistro.com.mx/politicas-de-privacidad/" target="_blank">https://tecnoregistro.com.mx/politicas-de-privacidad/</a>
							</small>
						</div>
					</div>
				</div>
			<!-- </div> -->
		</section>
		
		<script src="<?=URL_ROOT?>/assets/plugins/jquery/jquery.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/blockUI/jquery.blockUI.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/sweetalert/sweetalert.min.js"></script>
		<script src="<?=URL_ROOT?>/assets/plugins/md5/md5.min.js"></script>
		<script>
			$(function(){
				$(".preloader").fadeOut();
				$apiUrl = '<?= URL_ROOT ?>/';
				$('#reg-nombre').focus();
				var codigo = '';
				var id = '';

				$('#reg-tipo').change(function(){
					tipo = $(this).val();
					$('.invitado').toggleClass('hide',tipo != 'Invitado');
				});

				$data = {};
				$('#btnRegistro').click(function(e){
					e.preventDefault();
					btn = $(this);

					$data = {};
					$.each($('#frm-registro input, #frm-registro select'), function (index, elem) { 
						$(elem).removeClass('is-invalid');
						ide = $(elem).attr('id').replace('reg-','');
						valor = $.trim($(elem).val());
						$data[ide] = valor;
					});

					if($data.nombre == ''){
						$('#reg-nombre').addClass('is-invalid').focus();
					}else if($data.paterno == ''){
						$('#reg-paterno').addClass('is-invalid').focus();
					}else if($data.materno == ''){
						$('#reg-materno').addClass('is-invalid').focus();
					}else if($data.email == ''){
						$('#reg-email').addClass('is-invalid').focus();
					}else if($data.cargo == ''){
						$('#reg-cargo').addClass('is-invalid').focus();
					}else if($data.empresa == ''){
						$('#reg-empresa').addClass('is-invalid').focus();
					}else if($data.telefono == ''){
						$('#reg-telefono').addClass('is-invalid').focus();
					}/* else if($data.tipo == ''){
						$('#reg-tipo').addClass('is-invalid').focus();
					} */else if($data.tipo == 'Invitado' && $data.invitado == ''){
						$('#reg-invitado').addClass('is-invalid').focus();
					}else if($data.asiste == ''){
						$('#reg-asiste').addClass('is-invalid').focus();
					}else{
						blockPage();
						btn.addClass('disabled').prop('disabled', true);
						$.post($apiUrl+"registro/add/", $data,
							function (resp) {
								if(resp.response){
									codigo = resp.codigo; id = resp.result;
									$('#imgQR').attr('src', '/data/qr/'+resp.codigo+'.png')
									$('.display-5').html(resp.codigo);
									$('.dias').html($data.asiste);
									$('#message-success').addClass('alert').addClass('alert-success').removeClass('hide');
									$('#frm-registro').slideUp();
									$('#frm-res').slideDown();
									$('html, body').animate({ scrollTop: $("#logo").offset().top }, 1000);
								}else{

								}
								$.unblockUI();
							},
							"json"
						);
					}

				});

				$('#btnDescargar').click(function(e){
					e.preventDefault();
					window.open('<?= URL_ROOT ?>/registro/imprimir/'+codigo+'/'+id);
				})

				function blockPage(){
					$.blockUI({ 
						message: '<div class="spinner-grow text-primary" style="width: 3rem; height: 3rem;" role="status"><span class="sr-only">Loading...</span></div>',
						overlayCSS: {
							backgroundColor: '#1b2024',
							opacity: 0.8,
							zIndex: 1200000,
							cursor: 'wait'
						},
						css: {
							border: 0,
							color: '#fff',
							padding: 0,
							zIndex: 1200001,
							backgroundColor: 'transparent'
						}
					});
				}
			});
		</script>
	</body>

</html>